name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build Native
      run: cargo build --verbose
    - name: Setup WASM toolchain
      run: rustup target add wasm32-unknown-unknown
    - name: Build WASM
      run: cargo build --target=wasm32-unknown-unknown --verbose
    - name: Run tests and benchmarks
      run: |
        cargo test --verbose
        cargo run --release -p datachannel_socket_native_peer --example native_transport_benchmark -- --message-amount 10000 --warmup-messages 500 
        cargo run --release -p datachannel_socket_native_peer --example native_transport_benchmark -- --message-amount 100000 --warmup-messages 500
        cargo run --release -p datachannel_socket_native_peer --example native_transport_benchmark -- --message-amount 10000 --warmup-messages 500 
        cargo run --release -p datachannel_socket_native_peer --example native_transport_benchmark -- --message-amount 100000 --warmup-messages 500 
        cargo run --release -p datachannel_socket_native_peer --example native_transport_benchmark -- --message-amount 10000 --warmup-messages 500 
        cargo run --release -p datachannel_socket_native_peer --example native_transport_benchmark -- --message-amount 100000 --warmup-messages 500 